#Get Method
GET http://localhost:8081/api/home/homecont
Content-Type: application/json


# Add Method
###
POST http://localhost:8081/api/home/homecont
Content-Type: application/json

{
    "image": "Ini Gambar"
}

# Update Method
###
PUT http://localhost:8081/api/home/homecont/1

# Delete Method
###
DELETE http://localhost:8081/api/home/homecont/6